### ISSUE TITLE
regex_error at runtime

### ISSUE THREAD

**Issue by berniechow** [dillonl/graphite#12]
Running the graphite executable results in an error and termination of the program.

[centos@test bin]$ ./graphite -h
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted

**Comment by dillonl** [comment]
I think I took the regex stuff. Could you confirm that you have pulled down the latest changes.

**Comment by berniechow** [comment]
I pulled down the latest this morning.  I'm still getting the same error.  I'm using the following to build.  

cmake version 2.8.12.2
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

**Comment by dillonl** [comment]
Please use GCC 4.9.2 or greater, Graphite uses some newer features in C11.

**Comment by berniechow** [comment]
cmake was stuck using the system defined gcc.  To get cmake to use the newer updated gcc I had to set the following environmental variables:
`
export CC=/usr/local/bin/gcc
export CXX=/usr/local/bin/g++
`
Works now.  Thanks!
