### ISSUE TITLE
cc1plus: error: unrecognized command line option "-std=c++11"

### ISSUE THREAD

**Issue by zeeev** [dillonl/graphite#5]
Heads up.

cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: **\* [core/CMakeFiles/graphite_core.dir/util/Params.cpp.o] Error 1
make[1]: **\* [core/CMakeFiles/graphite_core.dir/all] Error 2

gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)

**Comment by dillonl** [comment]
Graphite requires c11. You'll have to update your compiler.
